# Generated by Django 5.0.6 on 2024-08-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_uservocabulary_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
