# Generated by Django 5.0.6 on 2024-07-01 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_en', models.CharField(blank=True, max_length=255, null=True)),
                ('translation_es', models.CharField(blank=True, max_length=255, null=True)),
                ('definition_en', models.TextField(blank=True, null=True)),
                ('definition_es', models.TextField(blank=True, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('example_translation_en', models.TextField(blank=True, null=True)),
                ('example_translation_es', models.TextField(blank=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.concept')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('singular_form', models.CharField(blank=True, max_length=100, null=True)),
                ('plural_form', models.CharField(blank=True, max_length=100, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.concept')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.language')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
