# Generated by Django 5.0.6 on 2024-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_concept_definition_language_word_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.IntegerField(default=0),
        ),
    ]
